services:
  - type: web
    name: retailiq-api
    runtime: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        value: ep-billowing-heart-b3b6dsss.c-4.ap-southeast-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0